"""add tenant_id and allowed_roles to document_chunks

Revision ID: 77843b8022af
Revises: e2b779038a8e
Create Date: 2026-09-08 14:08:03.659660

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77843b8022af"
down_revision: str | Sequence[str] | None = "e2b779038a8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("tenant_id", sa.String(length=100), server_default="default", nullable=False),
    )
    op.add_column(
        "document_chunks",
        sa.Column(
            "allowed_roles",
            sa.ARRAY(sa.String(length=100)).with_variant(sa.JSON(), "sqlite"),
            server_default="{*}",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_document_chunks_tenant_id"), "document_chunks", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_chunks_tenant_id"), table_name="document_chunks")
    op.drop_column("document_chunks", "allowed_roles")
    op.drop_column("document_chunks", "tenant_id")
    # ### end Alembic commands ###
