"""add heading_path and token_count to document_chunks

Revision ID: bd21a32003f2
Revises: c5cc997cbae6
Create Date: 2026-09-08 08:44:12.734842

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd21a32003f2"
down_revision: str | Sequence[str] | None = "c5cc997cbae6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema. (M7-2)

    ★ nullable=False + server_default가 짝인 이유 ★
    이미 들어 있는 행에도 값이 필요한데, 마이그레이션이 백필할 의미 있는 값이 없다 —
    heading_path는 원문을 다시 파싱해야 나오는 값이라 SQL로 만들 수 없다.
    server_default를 주면 Postgres가 기존 행을 그 값으로 채우고, 안 주면
    "column contains null values"로 실패한다. NULL 허용으로 도망가는 선택지도 있지만
    그러면 읽는 쪽 전부가 None을 다뤄야 한다.

    ★ 그래서 이 마이그레이션만으로는 끝이 아니다 ★ 기존 행의 heading_path는 빈
    문자열이라 검색 품질이 안 오른다. **문서를 재인입해야 실제 값이 채워진다** —
    스키마 변경과 데이터 채우기가 분리돼 있고, 후자는 배포 절차의 일부다.
    """
    op.add_column(
        "document_chunks",
        sa.Column("heading_path", sa.String(length=1000), server_default="", nullable=False),
    )
    op.add_column(
        "document_chunks",
        sa.Column("token_count", sa.Integer(), server_default="0", nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "token_count")
    op.drop_column("document_chunks", "heading_path")
    # ### end Alembic commands ###
