from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5cc997cbae6"
down_revision: str | Sequence[str] | None = "20260724_1448"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ★ autogenerate가 절대 만들어주지 않는 한 줄 ★
    # Alembic은 SQLAlchemy 메타데이터(테이블·컬럼·인덱스)를 DB와 비교하는데,
    # "확장"은 그 메타데이터에 없는 개념이라 diff에 잡히지 않는다.
    # 없으면 아래 create_table이 'type "vector" does not exist'로 실패한다.
    #
    # IF NOT EXISTS를 붙이는 이유: 마이그레이션은 여러 환경(로컬·CI·운영)에서
    # 돌고 이미 확장이 깔린 DB도 있다. 그런 곳에서 에러 없이 지나가야 한다.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # upgrade()의 역순으로 "이 마이그레이션이 만든 것"만 되돌린다.
    # 주의: 테이블을 지우면 인입된 청크 데이터도 같이 사라진다 — 원본 문서에서
    # 언제든 재인입할 수 있는 파생 데이터라 감수 가능하다(chunk.py 머리 주석 참고).
    op.drop_table("document_chunks")
    # 확장(vector)은 일부러 지우지 않는다. CREATE를 IF NOT EXISTS로 한 것과
    # 대칭 논리다 — 이미 확장이 깔려 있던 환경에서는 우리가 만든 게 아니므로,
    # 지우면 남의 것을 부순다. 나중에 vector 컬럼을 쓰는 다른 테이블이 생겼을
    # 때 이 downgrade가 그 테이블까지 망가뜨리는 사고도 함께 막는다.
